### ISSUE TITLE
Cannot read property 'sizes' of undefined

### ISSUE THREAD

**Issue by jdalton** [FormidableLabs/electron-webpack-dashboard#1]
Hi!

Using webpack-dashboard@v1.0.0-2 when I try to run my build command for [@std/esm](https://github.com/standard-things/esm) I ran into this error. The app is open and all that jazz.

```shell
/Users/jdalton/projects/esm/node_modules/webpack-dashboard/plugin/index.js:57
      inspectpack[action]({
                  ^
TypeError: Cannot read property 'sizes' of undefined
    at Promise.all.bundles.map.bundle (/Users/jdalton/projects/esm/node_modules/webpack-dashboard/plugin/index.js:57:19)
    at Array.map (<anonymous>)
    at INSPECTPACK_INDEPENDENT_ACTIONS.forEach.action 
```

**Comment by kenwheeler** [comment]
Hmmm, was this a watched build or a one off build? Where did the error surface?

**Comment by jdalton** [comment]
This is a one off build (no file watchers). The error surfaces during the build (from the console I initiated the build in)

**Comment by kenwheeler** [comment]
Nice snag, looks like the inspectpack daemon onlys get instantiated in watch mode. @tptee Any reason for that? Or can I just add it on invalidation?

**Comment by athomann** [comment]
I'm also getting an inspectpack error 
```
inspectpack/lib/parser/extractors.js:15
  const beginningIndex = pathInfoComment.indexOf(beginningToken);
                                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at extractPath (/Users/adamthomann/Documents/code/troops-web-ui/node_modules/inspectpack/lib/parser/extractors.js:15:41)

**Comment by kenwheeler** [comment]
@jdalton this is running build:prod?

@athomann is this a public repo?

**Comment by jdalton** [comment]
> @jdalton this is running build:prod?

This is running `npm run build` *(with the dashboard plugin added to the dev build, so non-prod build)*

**Comment by trevwaddell** [comment]
Hey, getting the same `TypeError: Cannot read property 'sizes' of undefined` error. Steps I took are below, using [this repo]( https://github.com/trevwaddell/react-starter ). 

1. npm installed webpackdashboard as described in the readme
2. added the plugin to the webpack config 
3. ran `npm start`

Afterwards, the 'sizes' error.

**Comment by athomann** [comment]
@kenwheeler currently not public.  Will work on reproducing in public repo.

**Comment by tcrosen** [comment]
Same problem, Dashboard won't work at all for me.  Trying to debug...

```
 95% emitting/Users/terry.rosen/Development/bap/node_modules/webpack-dashboard/plugin/index.js:57
      inspectpack[action]({
                 ^

TypeError: Cannot read property 'sizes' of undefined
    at Promise.all.bundles.map.bundle (/Users/terry.rosen/Development/bap/node_modules/webpack-dashboard/plugin/index.js:57:18)
    at Array.map (native)
    at INSPECTPACK_INDEPENDENT_ACTIONS.forEach.action (/Users/terry.rosen/Development/bap/node_modules/webpack-dashboard/plugin/index.js:56:25)
    at Array.forEach (native)
    at getBundleMetrics (/Users/terry.rosen/Development/bap/node_modules/webpack-dashboard/plugin/index.js:55:35)
    at Compiler.compiler.plugin.stats (/Users/terry.rosen/Development/bap/node_modules/webpack-dashboard/plugin/index.js:220:7)
    at Compiler.applyPlugins (/Users/terry.rosen/Development/bap/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/Users/terry.rosen/Development/bap/node_modules/webpack/lib/Compiler.js:268:11)
    at Compiler.emitRecords (/Users/terry.rosen/Development/bap/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/terry.rosen/Development/bap/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/terry.rosen/Development/bap/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/terry.rosen/Development/bap/node_modules/tapable/lib/Tapable.js:200:11)
    at Compiler.compiler.plugin (/Users/terry.rosen/Development/bap/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/terry.rosen/Development/bap/node_modules/tapable/lib/Tapable.js:204:13)
    at Compiler.afterEmit (/Users/terry.rosen/Development/bap/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/terry.rosen/Development/bap/node_modules/webpack/lib/Compiler.js:360:15)
    at /Users/terry.rosen/Development/bap/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/terry.rosen/Development/bap/node_modules/async/dist/async.js:998:13)
    at /Users/terry.rosen/Development/bap/node_modules/async/dist/async.js:906:16
    at /Users/terry.rosen/Development/bap/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by bntzio** [comment]
Same here, but the `electron-webpack-dashboard` is working fine for me (*I'm using the next.js next.config.js webpack config file*) like this:

```js
const DashboardPlugin = require('webpack-dashboard/plugin')

module.exports = {
  webpack: (config, { dev }) => {
    if (dev) {
      config.plugins.push(new DashboardPlugin())
    }

    return config
  }
}
```

Just that I'm getting the following `inspectpack` errors in my terminal.

```
TypeError: Cannot read property 'indexOf' of undefined
    at extractPath (/Users/hbendev/code/bntz/node_modules/inspectpack/lib/parser/extractors.js:15:41)
    at Function.nu (/Users/hbendev/code/bntz/node_modules/lodash/lodash.min.js:67:92)
    at /Users/hbendev/code/bntz/node_modules/lodash/lodash.min.js:41:252
    at h (/Users/hbendev/code/bntz/node_modules/lodash/lodash.min.js:7:90)
    at kr (/Users/hbendev/code/bntz/node_modules/lodash/lodash.min.js:41:220)
    at zn.On.toJSON.On.valueOf.On.value (/Users/hbendev/code/bntz/node_modules/lodash/lodash.min.js:136:81)
    at Object.getFileName (/Users/hbendev/code/bntz/node_modules/lodash/lodash.min.js:49:85)
    at webpackSections.forEach.element (/Users/hbendev/code/bntz/node_modules/inspectpack/lib/parser/index.js:38:33)
    at Array.forEach (native)
    at extractFromArrayExpression (/Users/hbendev/code/bntz/node_modules/inspectpack/lib/parser/index.js:20:19)
/Users/hbendev/code/bntz/node_modules/inspectpack/lib/models/bundle.js:43
    throw new Error("No code sections found");
```

```
Error: No code sections found
    at Bundle.validate (/Users/hbendev/code/bntz/node_modules/inspectpack/lib/models/bundle.js:43:11)
    at Immediate.setImmediate (/Users/hbendev/code/bntz/node_modules/inspectpack/lib/models/bundle.js:268:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
/Users/hbendev/code/bntz/node_modules/inspectpack/lib/models/bundle.js:43
    throw new Error("No code sections found");
```

What could it be? 🤔

**Comment by sbeland13** [comment]
Getting both issues, first with a one-off build using gulp:
```
inspectpack[action]({
                 ^

TypeError: Cannot read property 'sizes' of undefined
    at Promise.all.bundles.map.bundle (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack-dashboard/plugin/index.js:57:18)
    at Array.map (native)
    at INSPECTPACK_INDEPENDENT_ACTIONS.forEach.action (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack-dashboard/plugin/index.js:56:25)
    at Array.forEach (native)
    at getBundleMetrics (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack-dashboard/plugin/index.js:55:35)
    at Compiler.compiler.plugin.stats (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack-dashboard/plugin/index.js:220:7)
    at Compiler.applyPlugins (/Users/stefan/Documents/Development/roam-usa/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack/lib/Compiler.js:268:11)
    at Compiler.emitRecords (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/stefan/Documents/Development/roam-usa/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/stefan/Documents/Development/roam-usa/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/stefan/Documents/Development/roam-usa/node_modules/webpack/lib/Compiler.js:354:15)
```
And then instead ran webpack directly with the --watch flag, everything in the dashboard seems to be there and working but I am hitting this error in the terminal: 
```
/Users/stefan/Documents/Development/roam-usa/node_modules/inspectpack/lib/parser/extractors.js:15
  const beginningIndex = pathInfoComment.indexOf(beginningToken);
                                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at extractPath (/Users/stefan/Documents/Development/roam-usa/node_modules/inspectpack/lib/parser/extractors.js:15:41)
    at Function.nu (/Users/stefan/Documents/Development/roam-usa/node_modules/lodash/lodash.min.js:67:92)
    at /Users/stefan/Documents/Development/roam-usa/node_modules/lodash/lodash.min.js:41:252
    at h (/Users/stefan/Documents/Development/roam-usa/node_modules/lodash/lodash.min.js:7:90)
    at kr (/Users/stefan/Documents/Development/roam-usa/node_modules/lodash/lodash.min.js:41:220)
    at zn.On.toJSON.On.valueOf.On.value (/Users/stefan/Documents/Development/roam-usa/node_modules/lodash/lodash.min.js:136:81)
    at Object.getFileName (/Users/stefan/Documents/Development/roam-usa/node_modules/lodash/lodash.min.js:49:85)
    at node.properties.forEach.property (/Users/stefan/Documents/Development/roam-usa/node_modules/inspectpack/lib/parser/index.js:63:33)
    at Array.forEach (native)
    at extractFromObjectExpression (/Users/stefan/Documents/Development/roam-usa/node_modules/inspectpack/lib/parser/index.js:62:19)
```

**Comment by kenwheeler** [comment]
Just pushed out a new release. @jdalton still getting an unexpected Token name (TokenType) on std/esm, but the dashboard runs. Thinking it has something to with the uglify minification for estimated min sizes. I'll ticket that out separately.

Everyone else, install the latest version of the plugin and the app and you should be all set.

**Comment by ryan-roemer** [comment]
> Thinking it has something to with the uglify minification for estimated min sizes. I'll ticket that out separately.

@kenwheeler -- I'm guessing that would be best as an `inspectpack` ticket. We can switch to babilii or is there a newer es-friendly uglify?

**Comment by kenwheeler** [comment]
@ryan-roemer theres this https://github.com/mishoo/UglifyJS2

**Comment by ryan-roemer** [comment]
Yeah, from that it looks like https://www.npmjs.com/package/uglify-es might work.

**Comment by jdalton** [comment]
For the webpack-uglify plugin there's [v1.0.0-beta.2](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/tree/v1.0.0-beta.2) which is Uglify v3.
