### ISSUE TITLE
Error in terminal after webpack builds (TypeError: Cannot read property 'indexOf' of undefined)

### ISSUE THREAD

**Issue by chadwatson** [FormidableLabs/electron-webpack-dashboard#10]
First of all, awesome project! Really stoked to add it to my development workflow.

This error is being thrown three times in my terminal after every webpack build.

```
const beginningIndex = pathInfoComment.indexOf(beginningToken);
                                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at Object.extractPath (/Users/cwatson/git/virtualkeypad-browser/node_modules/inspectpack/lib/parser/extractors.js:15:41)
    at Object.getFileName (/Users/cwatson/git/virtualkeypad-browser/node_modules/lodash/lodash.min.js:38:477)
    at webpackSections.forEach.element (/Users/cwatson/git/virtualkeypad-browser/node_modules/inspectpack/lib/parser/index.js:38:33)
    at Array.forEach (native)
    at extractFromArrayExpression (/Users/cwatson/git/virtualkeypad-browser/node_modules/inspectpack/lib/parser/index.js:20:19)
    at node (/Users/cwatson/git/virtualkeypad-browser/node_modules/inspectpack/lib/parser/index.js:87:7)
    at traverseFast (/Users/cwatson/git/virtualkeypad-browser/node_modules/babel-types/lib/index.js:744:3)
    at traverseFast (/Users/cwatson/git/virtualkeypad-browser/node_modules/babel-types/lib/index.js:777:9)
    at traverseFast (/Users/cwatson/git/virtualkeypad-browser/node_modules/babel-types/lib/index.js:780:7)
    at traverseFast (/Users/cwatson/git/virtualkeypad-browser/node_modules/babel-types/lib/index.js:777:9)
```

It doesn't seem to be breaking anything in the application that I can tell.

I'm instantiating webpack-dashboard here:

```
/* eslint-disable global-require */
const express = require('express')
const path = require('path')
const compression = require('compression')
const pkg = require(path.resolve(process.cwd(), 'package.json')) // eslint-disable-line import/no-dynamic-require

// Dev middleware
const addDevMiddlewares = (app, webpackConfig) => {
  const webpack = require('webpack')
  const webpackDevMiddleware = require('webpack-dev-middleware')
  const webpackHotMiddleware = require('webpack-hot-middleware')
  const DashboardPlugin = require('webpack-dashboard/plugin')
  const compiler = webpack(webpackConfig)
  compiler.apply(new DashboardPlugin())
  const middleware = webpackDevMiddleware(compiler, {
    noInfo: true,
    publicPath: webpackConfig.output.publicPath,
    quiet: true,
    stats: 'errors-only',
  })

  app.use(middleware)
  app.use(webpackHotMiddleware(compiler, {
    log: () => {},
  }))

  // Since webpackDevMiddleware uses memory-fs internally to store build
  // artifacts, we use it instead
  const fs = middleware.fileSystem

  if (pkg.dllPlugin) {
    app.get(/\.dll\.js$/, (req, res) => {
      const filename = req.path.replace(/^\//, '')
      res.sendFile(path.join(process.cwd(), pkg.dllPlugin.path, filename))
    })
  }

  app.get('*', (req, res) => {
    fs.readFile(path.join(compiler.outputPath, 'index.html'), (err, file) => {
      if (err) {
        res.sendStatus(404)
      } else {
        res.send(file.toString())
      }
    })
  })
}
```

**OS: MacOS 10.12.6**
**webpack@3.3.5**
**webpack-dashboard@v1.0.0-2**

**Comment by ryan-roemer** [comment]
This is mentioned in #1 but we can separate it out here.

I'm not sure exactly what's up, but my guess is that the bundle isn't `inspectpack` friendly and is barfing on not having a `pathinfo` comment. I'm working on making that code more permissive anyways to handle the DLL plugin code, so watch https://github.com/FormidableLabs/inspectpack/compare/chore/playbook-tests for updates.

/cc @kenwheeler

**Comment by ryan-roemer** [comment]
@chadwatson -- What is the underlying code at issue? Is by chance a DLL shared library?

**Comment by chadwatson** [comment]
I'm using React Boilerplate.

**Comment by chadwatson** [comment]
Noticed that you had some questions about that here https://github.com/react-boilerplate/react-boilerplate/issues/319

**Comment by ryan-roemer** [comment]
Can you look at your bundles and see if you have DLL plugin usage?

Grepping on `module.exports = __webpack_require__;` should probably work to tell if you don't otherwise know that you're looking for. Oh, and there would definitely be multiple files.

**Comment by chadwatson** [comment]
I didn't get any results. So I guess not.
