### ISSUE TITLE
TypeError: Cannot read property 'sizes' of undefined

### ISSUE THREAD

**Issue by jessehattabaugh** [FormidableLabs/electron-webpack-dashboard#17]
Mac 10.12.6
Node 8.2.1
Webpack 2.6.1

> /Users/jesse/Code/web/frontend/node_modules/webpack-dashboard/plugin/index.js:57
>       inspectpack[action]({
>                  ^
> 
> TypeError: Cannot read property 'sizes' of undefined
>     at Promise.all.bundles.map.bundle (/Users/jesse/Code/web/frontend/node_modules/webpack-dashboard/plugin/index.js:57:18)
>     at Array.map (native)
>     at INSPECTPACK_INDEPENDENT_ACTIONS.forEach.action (/Users/jesse/Code/web/frontend/node_modules/webpack-dashboard/plugin/index.js:56:25)
>     at Array.forEach (native)
>     at getBundleMetrics (/Users/jesse/Code/web/frontend/node_modules/webpack-dashboard/plugin/index.js:55:35)
>     at Compiler.compiler.plugin.stats (/Users/jesse/Code/web/frontend/node_modules/webpack-dashboard/plugin/index.js:220:7)
>     at Compiler.applyPlugins (/Users/jesse/Code/web/frontend/node_modules/tapable/lib/Tapable.js:61:14)
>     at /Users/jesse/Code/web/frontend/node_modules/webpack/lib/Compiler.js:271:13
>     at Compiler.emitRecords (/Users/jesse/Code/web/frontend/node_modules/webpack/lib/Compiler.js:367:37)
>     at /Users/jesse/Code/web/frontend/node_modules/webpack/lib/Compiler.js:265:12
>     at /Users/jesse/Code/web/frontend/node_modules/webpack/lib/Compiler.js:360:11
>     at next (/Users/jesse/Code/web/frontend/node_modules/tapable/lib/Tapable.js:154:11)
>     at Compiler.compiler.plugin (/Users/jesse/Code/web/frontend/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
>     at Compiler.applyPluginsAsyncSeries1 (/Users/jesse/Code/web/frontend/node_modules/tapable/lib/Tapable.js:158:13)
>     at Compiler.afterEmit (/Users/jesse/Code/web/frontend/node_modules/webpack/lib/Compiler.js:357:8)
>     at Compiler.<anonymous> (/Users/jesse/Code/web/frontend/node_modules/webpack/lib/Compiler.js:352:14)
>     at /Users/jesse/Code/web/frontend/node_modules/async/dist/async.js:421:16
>     at iteratorCallback (/Users/jesse/Code/web/frontend/node_modules/async/dist/async.js:998:13)
>     at /Users/jesse/Code/web/frontend/node_modules/async/dist/async.js:906:16
>     at /Users/jesse/Code/web/frontend/node_modules/graceful-fs/graceful-fs.js:43:10
>     at FSReqWrap.oncomplete (fs.js:135:15)

**Comment by jessehattabaugh** [comment]
I just tried running with `webpack-dev-server` instead of just `webpack` and this didn't occur.

**Comment by kenwheeler** [comment]
hmm. was there any error on build?

**Comment by maccuaa** [comment]
I had the same error on Windows using Express.

```
webpack: Compiled successfully.
Error from inspectpack: TypeError: Cannot read property 'sizes' of undefined
    at Promise.all.bundles.map.bundle (F:\sbp\ui\node_modules\webpack-dashboard\plugin\index.js:55:18)
    at Array.map (native)
    at getSizes (F:\sbp\ui\node_modules\webpack-dashboard\plugin\index.js:54:13)
    at MapSink.event (F:\sbp\ui\node_modules\most\lib\fusion\Map.js:71:22)
    at PropagateTask.runJust [as _run] (F:\sbp\ui\node_modules\most\lib\source\core.js:46:8)
    at PropagateTask.run (F:\sbp\ui\node_modules\most\lib\scheduler\PropagateTask.js:43:8)
    at ScheduledTask.run (F:\sbp\ui\node_modules\most\lib\scheduler\ScheduledTask.js:20:20)
    at runTask (F:\sbp\ui\node_modules\most\lib\task.js:18:17)
    at runTasks (F:\sbp\ui\node_modules\most\lib\scheduler\Timeline.js:80:7)
    at Timeline.runTasks (F:\sbp\ui\node_modules\most\lib\scheduler\Timeline.js:69:20)
    at Scheduler._runReadyTasks (F:\sbp\ui\node_modules\most\lib\scheduler\Scheduler.js:107:17)
    at Asap.Scheduler._runReadyTasksBound [as f] (F:\sbp\ui\node_modules\most\lib\scheduler\Scheduler.js:29:10)
    at Asap.run (F:\sbp\ui\node_modules\most\lib\scheduler\ClockTimer.js:32:30)
    at runTask (F:\sbp\ui\node_modules\most\lib\task.js:18:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
F:\sbp\ui\node_modules\most\lib\fatalError.js:13
    throw e;
    ^

TypeError: Cannot read property 'terminate' of undefined
    at DashboardPlugin.cleanup (F:\sbp\ui\node_modules\webpack-dashboard\plugin\index.js:134:23)
    at Object.error (F:\sbp\ui\node_modules\webpack-dashboard\plugin\index.js:270:18)
    at throwError (F:\sbp\ui\node_modules\most\lib\observable\subscribe.js:86:18)
    at F:\sbp\ui\node_modules\most\lib\observable\subscribe.js:71:5
    at process._tickCallback (internal/process/next_tick.js:109:7)
error Command failed with exit code 1.
```

**Comment by kenwheeler** [comment]
@jessehattabaugh this should be resolved using the latest builds of webpack-dashboard and the app.

**Comment by kenwheeler** [comment]
@maccuaa what platform is this happening on. Sounds like the daemon is failing to initialize. Are you on latest?

**Comment by maccuaa** [comment]
Reinstalling everything seems to have fixed the issue.   Now however I am having a similar issue as #20.  Only one process is spawned (I presume the webpack-dashboard process) but it rapidly starts eating up memory until it runs out of memory and dies.  

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
That being said it isn't an issue for this project, if you like I can raise it on webpack-dashboard.

**Comment by kenwheeler** [comment]
Yeah please ticket it there
